---
- hosts: db
  become: true
  tasks:
   - name: update all packages
     yum: name=* state=latest
   - name: Ensure NTP (for time synchronization) is installed.
     yum: name=ntp state=installed
   - name: Ensure NTP is running.
     service: name=ntpd state=started enabled=yes
